---
refresh_interval: 2 # seconds
max_price: 12750 # dollars/euros/etc
urls:
  - https://www.alza.cz/gigabyte-gt-1030-silent-low-profile-2g-d4977528.htm # test
  - https://www.alza.cz/gaming/asus-dual-geforce-rtx-3060-ti-o8g-d6270687.htm
  - https://www.alza.cz/gaming/asus-tuf-geforce-rtx-3060-ti-gaming-o8g-d6270689.htm
  - https://www.alza.cz/gaming/asus-rog-strix-geforce-rtx-3060-ti-gaming-o8g-d6270688.htm
  - https://www.alza.cz/evga-geforce-rtx-3060-ti-xc-black-d6255253.htm
  - https://www.alza.cz/evga-geforce-rtx-3060-ti-xc-d6255522.htm
  - https://www.alza.cz/evga-geforce-rtx-3060-ti-ftw3-d6255251.htm
  - https://www.alza.cz/evga-geforce-rtx-3060-ti-ftw3-black-d6255523.htm
  - https://www.alza.cz/evga-geforce-rtx-3060-ti-ftw3-ultra-d6255524.htm
  - https://www.alza.cz/gaming/gainward-geforce-rtx-3060-ti-ghost-d6243691.htm
  - https://www.alza.cz/gaming/gainward-geforce-rtx-3060-ti-ghost-oc-d6243688.htm
  - https://www.alza.cz/gaming/gainward-geforce-rtx-3060-ti-phoenix-d6243690.htm
  - https://www.alza.cz/gaming/gainward-geforce-rtx-3060-ti-phoenix-gs-d6243692.htm
  - https://www.alza.cz/gaming/gigabyte-geforce-rtx-3060-ti-eagle-8g-d6255495.htm
  - https://www.alza.cz/gaming/gigabyte-geforce-rtx-3060-ti-eagle-oc-8g-d6255496.htm
  - https://www.alza.cz/gaming/gigabyte-geforce-rtx-3060-ti-gaming-oc-8g-d6255497.htm
  - https://www.alza.cz/gaming/gigabyte-geforce-rtx-3060-ti-gaming-oc-pro-8g-d6255498.htm
  - https://www.alza.cz/gaming/gigabyte-aorus-geforce-rtx-3060-ti-master-8g-d6248416.htm
  - https://www.alza.cz/gaming/inno3d-geforce-rtx-3060-ti-ichill-x3-d6255499.htm
  - https://www.alza.cz/msi-geforce-rtx-3060-ti-ventus-2x-oc-d6270353.htm
  - https://www.alza.cz/msi-geforce-rtx-3060-ti-ventus-3x-oc-d6270354.htm
  - https://www.alza.cz/msi-geforce-rtx-3060-ti-gaming-x-trio-d6270352.htm
...