---
refresh_interval: 2 # seconds
max_price: 15500 # dollars/euros/etc
urls:
  - https://www.alza.cz/gigabyte-gt-1030-silent-low-profile-2g-d4977528.htm # test
  - https://www.alza.cz/asrock-radeon-rx-6800-16g-d6244319.htm
  - https://www.alza.cz/gaming/asrock-radeon-rx-6800-challenger-pro-16g-oc-d6255249.htm
  - https://www.alza.cz/sapphire-amd-radeon-rx-6800-16g-d6244445.htm
  - https://www.alza.cz/gaming/sapphire-nitro-radeon-rx-6800-16g-d6244617.htm
...